os: linux
language: node_js
node_js: node
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- if [ ${TRAVIS_EVENT_TYPE} = "cron" ];
  then yarn cron;
  else yarn build;
  fi
after_script: greenkeeper-lockfile-upload
after_success:
- if [ ${TRAVIS_EVENT_TYPE} = "cron" ];
  then bash cron/cron.sh;
  elif [ ${TRAVIS_PULL_REQUEST} = "false" ];
  then bash deploy.sh;
  else echo "Nothing to deploy";
  fi
notifications:
  email: false
