os: linux
language: node_js
node_js: node
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
script:
- if [ ${TRAVIS_EVENT_TYPE} = "cron" ];
  then KITSU_USERNAME=$KITSU_USERNAME KITSU_PASSWORD=$KITSU_PASSWORD stdbuf -i0 -o0 -e0 yarn cron;
  else stdbuf -i0 -o0 -e0 yarn build && yarn limit;
  fi
after_success:
- if [ ${TRAVIS_EVENT_TYPE} = "cron" ];
  then bash cron/cron.sh;
  fi
