os: linux
language: node_js
node_js: 9 # return to 'node' when https://github.com/anodynos/upath/pull/15 merged
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
script:
- if [ ${TRAVIS_EVENT_TYPE} = "cron" ];
  then yarn cron;
  else yarn build;
  fi
after_success:
- if [ ${TRAVIS_EVENT_TYPE} = "cron" ];
  then bash cron/cron.sh;
  fi
