name: Daily Update

on:
  schedule:
  - cron: '0 23 * * *' # Every night at 23:00

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get Yarn cache directory
      id: yarn-cache-dir-path
      run: echo '::set-output name=dir::$(yarn cache dir)'

    - name: Use Yarn cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn install --prefer-offline --frozen-lockfile

    - name: Get seasonal data from Kitsu.io
      run: yarn cron
      with:
        KITSU_USERNAME: ${{ secrets.KITSU_USERNAME }}
        KITSU_PASSWORD: ${{ secrets.KITSU_PASSWORD }}

    - name: Commit updated seasonal data
      run: |
        git config --global user.name '${{ secrets.GH_USERNAME }}'
        git config --global user.email '${{ secrets.GH_EMAIL }}'
        git commit -am 'chore: add data for $(date +%F)'
        git push
